# Generated by Django 3.1.3 on 2020-11-14 02:19

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=40, unique=True, verbose_name='勘定科目')),
                ('furigana', models.CharField(blank=True, max_length=30, null=True, unique=True, verbose_name='ふりがな')),
                ('description', models.CharField(blank=True, max_length=500, null=True, verbose_name='説明')),
            ],
            options={
                'db_table': 'account',
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30, unique=True, verbose_name='カテゴリー名')),
            ],
            options={
                'db_table': 'name',
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('order', models.IntegerField(verbose_name='順番')),
                ('debitCredit', models.IntegerField(choices=[(0, '借方'), (1, '貸方')], verbose_name='借方(0)貸方(1)')),
                ('money', models.IntegerField(verbose_name='金額')),
                ('date', models.DateField(verbose_name='日付')),
                ('memo', models.CharField(blank=True, max_length=200, null=True, verbose_name='備考')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='account', to='bookkeeping.account', verbose_name='勘定科目')),
            ],
            options={
                'db_table': 'transaction',
                'ordering': ['-date', 'order', 'debitCredit'],
            },
        ),
    ]
