# Generated by Django 3.1.3 on 2020-12-03 05:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bookkeeping', '0002_auto_20201202_0940'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Category',
            new_name='AccountCategory',
        ),
        migrations.RemoveField(
            model_name='account',
            name='isActive',
        ),
        migrations.RemoveField(
            model_name='currency',
            name='isActive',
        ),
        migrations.RemoveField(
            model_name='tax',
            name='isActive',
        ),
        migrations.AlterField(
            model_name='account',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='作成ユーザー'),
        ),
        migrations.CreateModel(
            name='ExcludedTax',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookkeeping.tax')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='作成ユーザー')),
            ],
            options={
                'abstract': False,
                'unique_together': {('user', 'item')},
            },
        ),
        migrations.CreateModel(
            name='ExcludedDepartment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookkeeping.department')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='作成ユーザー')),
            ],
            options={
                'abstract': False,
                'unique_together': {('user', 'item')},
            },
        ),
        migrations.CreateModel(
            name='ExcludedCurrency',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookkeeping.currency')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='作成ユーザー')),
            ],
            options={
                'abstract': False,
                'unique_together': {('user', 'item')},
            },
        ),
        migrations.CreateModel(
            name='ExcludedAccount',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookkeeping.account')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='作成ユーザー')),
            ],
            options={
                'abstract': False,
                'unique_together': {('user', 'item')},
            },
        ),
    ]
