# Generated by Django 3.1.3 on 2020-11-14 03:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookkeeping', '0002_auto_20201114_1119'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='account',
            options={'ordering': ['category', '-name']},
        ),
    ]
