# Generated by Django 3.1.3 on 2020-12-05 04:35

import bookkeeping.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookkeeping', '0003_auto_20201203_1409'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='code',
            field=models.CharField(max_length=30, unique=True, validators=[django.core.validators.RegexValidator(message='半角数字・または半角大文字アルファベットで入力してください。例: AZ123', regex='^[0-9A-Z]+$')], verbose_name='コード'),
        ),
        migrations.AlterField(
            model_name='department',
            name='code',
            field=models.CharField(max_length=30, unique=True, validators=[django.core.validators.RegexValidator(message='半角数字・または半角大文字アルファベットで入力してください。例: AZ123', regex='^[0-9A-Z]+$')], verbose_name='コード'),
        ),
        migrations.AlterField(
            model_name='tax',
            name='code',
            field=models.CharField(max_length=30, unique=True, validators=[django.core.validators.RegexValidator(message='半角数字・または半角大文字アルファベットで入力してください。例: AZ123', regex='^[0-9A-Z]+$')], verbose_name='コード'),
        ),
        migrations.AlterField(
            model_name='transactiongroup',
            name='pdf',
            field=models.FileField(blank=True, null=True, upload_to=bookkeeping.models.pdf_file_path),
        ),
    ]
