# Generated by Django 3.1.3 on 2020-11-17 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookkeeping', '0003_auto_20201114_1229'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='order',
            field=models.IntegerField(default=0, verbose_name='順番'),
            preserve_default=False,
        ),
    ]
