# Generated by Django 3.1.3 on 2020-12-05 05:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookkeeping', '0004_auto_20201205_1335'),
    ]

    operations = [
        migrations.RenameField(
            model_name='currency',
            old_name='currency',
            new_name='code',
        ),
    ]
