# Generated by Django 3.1.3 on 2020-12-09 07:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookkeeping', '0005_auto_20201205_1433'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transaction',
            options={'ordering': ['-group', 'debitCredit', 'order']},
        ),
    ]
