# Generated by Django 3.1.3 on 2020-12-13 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookkeeping', '0006_auto_20201209_1654'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='foreignMoney',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=13, null=True, verbose_name='金額（海外通貨）'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='money',
            field=models.DecimalField(decimal_places=0, max_digits=11, verbose_name='金額（円）'),
        ),
    ]
