# Generated by Django 3.1.3 on 2020-12-16 08:28

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bookkeeping', '0008_auto_20201216_1415'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='transactiongroup',
            unique_together={('date', 'slipNum', 'user')},
        ),
    ]
