# Generated by Django 3.1.3 on 2020-12-18 02:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookkeeping', '0009_auto_20201216_1728'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactiongroup',
            name='currency',
            field=models.ForeignKey(default='JPY', on_delete=django.db.models.deletion.PROTECT, to='bookkeeping.currency'),
        ),
    ]
