# Generated by Django 3.1.3 on 2020-12-19 00:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookkeeping', '0010_auto_20201218_1132'),
    ]

    operations = [
        migrations.RenameField(
            model_name='currency',
            old_name='title',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='tax',
            old_name='title',
            new_name='name',
        ),
    ]
