# Generated by Django 3.1.6 on 2021-02-16 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookkeeping', '0011_auto_20201219_0951'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='account',
            options={'ordering': ['category', 'code']},
        ),
    ]
