version: 2.1

executors:
  backend-executor:
    docker:
      - image: circleci/python:3.9.0
        environment:
          PYTHONBUFFERED: 1
          SECRET_KEY: SECRET_KEY
          DATABASE_ENGINE: django.db.backends.postgresql
          DATABASE_DB: django_db
          DATABASE_USER: django_db_user
          DATABASE_PASSWORD: password1234
          DATABASE_HOST: localhost
          DATABASE_PORT: 5432
          DATABASE: postgres
          DJANGO_ALLOWED_HOSTS: localhost 127.0.0.1 [::1]
          TWITTER_CONSUMER_KEY: SAMPLE
          TWITTER_CONSUMER_SECRET: SAMPLE
          API_URL: http://localhost:8000
          FRONTEND_URL: http://localhost:3000
      - image: circleci/postgres:12.1-alpine
        environment:
          POSTGRES_USER: django_db_user
          POSTGRES_PASSWORD: password1234
          POSTGRES_DB: django_db
  frontend-executor:
    docker:
      - image: circleci/node:14.14.0

commands:
  pip_install:
    description: "pip install を実行"
    steps:
      - run:
          name: pip install
          command: sudo pip3 install -r backend/requirements.txt

jobs:
  backend_build:
    executor: backend-executor
    steps:
      - checkout
      - run: sudo chown -R circleci:circleci /usr/local/bin
      - run: sudo chown -R circleci:circleci /usr/local/lib/python3.9/site-packages
      - pip_install
      - run:
          working_directory: backend
          command: python manage.py test
      - store_test_results:
          path: test-results
      - store_artifacts:
          path: test-reports

workflows:
  version: 2.1
  backend-test:
    jobs:
      - backend_build
