# Generated by Django 3.1.6 on 2021-02-18 10:21

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AmebaDepartment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('code', models.CharField(max_length=30, unique=True, validators=[django.core.validators.RegexValidator(message='半角数字・または半角大文字アルファベットで入力してください。例: AZ123', regex='^[0-9A-Z]+$')], verbose_name='コード')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='作成ユーザー')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('payment', models.DecimalField(decimal_places=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0)], verbose_name='時給')),
                ('position', models.IntegerField(choices=[(0, '正規'), (1, '非正規')], verbose_name='労働区分')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ameba.amebadepartment', verbose_name='部門')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='作成ユーザー')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='WorkingHours',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField(verbose_name='日付')),
                ('hours', models.DecimalField(decimal_places=1, max_digits=3, validators=[django.core.validators.MinValueValidator(0.1), django.core.validators.MaxValueValidator(24)], verbose_name='労働時間')),
                ('laborCost', models.DecimalField(decimal_places=2, max_digits=7, validators=[django.core.validators.MinValueValidator(0.01)], verbose_name='人件費')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ameba.employee', verbose_name='費用項目')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='作成ユーザー')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SalesUnit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('unitPrice', models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='販売単価')),
                ('department', models.ManyToManyField(to='ameba.AmebaDepartment', verbose_name='部門')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='作成ユーザー')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Sales',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField(verbose_name='日付')),
                ('num', models.DecimalField(blank=True, decimal_places=0, default=1, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='売上個数')),
                ('money', models.DecimalField(decimal_places=2, max_digits=9, validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='売上高')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ameba.amebadepartment', verbose_name='部門')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ameba.salesunit', verbose_name='売上項目')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='作成ユーザー')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CostItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='作成ユーザー')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Cost',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField(verbose_name='日付')),
                ('money', models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(0)], verbose_name='費用金額')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ameba.amebadepartment', verbose_name='部門')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ameba.costitem', verbose_name='費用項目')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='作成ユーザー')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
