# Generated by Django 3.1.6 on 2021-02-18 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ameba', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='salesunit',
            old_name='department',
            new_name='departments',
        ),
    ]
