# Generated by Django 3.1.6 on 2021-02-19 00:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ameba', '0002_auto_20210218_2102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sales',
            name='item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='ameba.salesunit', verbose_name='売上項目'),
        ),
    ]
