# Generated by Django 3.1.7 on 2021-02-28 03:24

import ameba.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import functools
import imagekit.models.fields
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ameba', '0003_auto_20210219_0938'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='furigana',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='ふりがな'),
        ),
        migrations.AddField(
            model_name='employee',
            name='photo',
            field=imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to=functools.partial(ameba.models.get_image_path, *(), **{'folder_name': 'employees'})),
        ),
        migrations.AddField(
            model_name='salesunit',
            name='photo',
            field=imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to=functools.partial(ameba.models.get_image_path, *(), **{'folder_name': 'sales_units'})),
        ),
        migrations.AlterField(
            model_name='employee',
            name='position',
            field=models.IntegerField(choices=[(0, '正社員'), (1, 'アルバイト')], verbose_name='労働区分'),
        ),
        migrations.CreateModel(
            name='SalesCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='作成ユーザー')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
