# Generated by Django 3.1.7 on 2021-02-28 03:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ameba', '0004_auto_20210228_1224'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesunit',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='ameba.salescategory'),
        ),
    ]
