# Generated by Django 3.1.7 on 2021-02-28 11:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ameba', '0006_auto_20210228_2006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cost',
            name='money',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='費用金額'),
        ),
    ]
