# Generated by Django 3.1.7 on 2021-03-01 00:30

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ameba', '0007_auto_20210228_2008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='amebadepartment',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='costitem',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='employee',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='salescategory',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='salesunit',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name='amebadepartment',
            unique_together={('user', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='costitem',
            unique_together={('user', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='employee',
            unique_together={('user', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='salescategory',
            unique_together={('user', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='salesunit',
            unique_together={('user', 'name')},
        ),
    ]
