# Generated by Django 3.1.7 on 2021-03-02 23:18

import ameba.models
from django.db import migrations, models
import functools
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('ameba', '0008_auto_20210301_0930'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='firstName',
            field=models.CharField(default='太郎', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employee',
            name='furiganaFirstName',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='ふりがな（名）'),
        ),
        migrations.AddField(
            model_name='employee',
            name='furiganaLastName',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='ふりがな（姓）'),
        ),
        migrations.AddField(
            model_name='employee',
            name='lastName',
            field=models.CharField(default='田中', max_length=30, verbose_name='姓'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='employee',
            name='photo',
            field=imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to=functools.partial(ameba.models.get_image_path, *(), **{'folder_name': 'employees'}), verbose_name='写真'),
        ),
        migrations.AlterUniqueTogether(
            name='employee',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='employee',
            name='furigana',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='name',
        ),
    ]
