# Generated by Django 3.1.7 on 2021-03-10 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ameba', '0009_auto_20210303_0818'),
    ]

    operations = [
        migrations.AlterField(
            model_name='amebadepartment',
            name='name',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='costitem',
            name='name',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='employee',
            name='firstName',
            field=models.CharField(max_length=30, verbose_name='名'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='furiganaFirstName',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='ふりがな（名）'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='furiganaLastName',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='ふりがな（姓）'),
        ),
        migrations.AlterField(
            model_name='salescategory',
            name='name',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='salesunit',
            name='name',
            field=models.CharField(max_length=30),
        ),
    ]
